### ISSUE TITLE
视频自动发布报错

### ISSUE THREAD

**Issue by mky3** [ddean2009/MoneyPrinterPlus#16]
2024-07-19 10:45:07.531 Uncaught app exception
Traceback (most recent call last):
  File "D:\MoneyPrinterPlus\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "D:\MoneyPrinterPlus\pages\03_auto_publish.py", line 222, in <module>
    video_list = get_file_map_from_dir(st.session_state["video_publish_content_dir"], ".mp4")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MoneyPrinterPlus\tools\utils.py", line 71, in get_file_map_from_dir
    file_dir = os.path.abspath(file_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 580, in abspath
  File "<frozen ntpath>", line 547, in normpath
TypeError: expected str, bytes or os.PathLike object, not NoneType
2024-07-19 10:48:06.893 Uncaught app exception
Traceback (most recent call last):
  File "D:\MoneyPrinterPlus\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "D:\MoneyPrinterPlus\pages\03_auto_publish.py", line 222, in <module>
    video_list = get_file_map_from_dir(st.session_state["video_publish_content_dir"], ".mp4")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MoneyPrinterPlus\tools\utils.py", line 71, in get_file_map_from_dir
    file_dir = os.path.abspath(file_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 580, in abspath
  File "<frozen ntpath>", line 547, in normpath
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by ddean2009** [comment]
看我的教程。  你这个是视频发布目录没有设置
