### ISSUE TITLE
这是什么问题呀，求大佬指教！感谢感谢！！！

### ISSUE THREAD

**Issue by Ch712** [ddean2009/MoneyPrinterPlus#26]
IndexError: list index out of range
Traceback:
File "D:\MoneyPrinterPlus-main\MoneyPrinterPlus-main\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
File "D:\MoneyPrinterPlus-main\MoneyPrinterPlus-main\venv\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
File "D:\MoneyPrinterPlus-main\MoneyPrinterPlus-main\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
File "D:\MoneyPrinterPlus-main\MoneyPrinterPlus-main\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
File "D:\MoneyPrinterPlus-main\MoneyPrinterPlus-main\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
File "D:\MoneyPrinterPlus-main\MoneyPrinterPlus-main\pages\01_auto_video.py", line 66, in generate_video
    main_generate_ai_video(video_generator)
File "D:\MoneyPrinterPlus-main\MoneyPrinterPlus-main\main.py", line 268, in main_generate_ai_video
    main_generate_subtitle()
File "D:\MoneyPrinterPlus-main\MoneyPrinterPlus-main\main.py", line 257, in main_generate_subtitle
    generate_caption()
File "D:\MoneyPrinterPlus-main\MoneyPrinterPlus-main\services\captioning\captioning_service.py", line 75, in generate_caption
    captioning.finish()
File "D:\MoneyPrinterPlus-main\MoneyPrinterPlus-main\services\captioning\common_captioning_service.py", line 204, in finish
    for caption in self.captions_from_offline_results():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\MoneyPrinterPlus-main\MoneyPrinterPlus-main\services\captioning\common_captioning_service.py", line 187, in captions_from_offline_results
    last_caption = captions[-1]
                   ~~~~~~~~^^^^

**Comment by ddean2009** [comment]
完整日志发一下， 这种一般是字幕没生成。 原因是云服务有些功能没开。

**Comment by todrinkhotwater** [comment]
我和他的报错一样 ，是按照操作一步一步来的目前排查不出来哪里api有问题 
是因为Azure AI services 那边的吗
这边api采用有点疑惑但是还不太懂怎么做
![image](https://github.com/user-attachments/assets/6ddf42f6-cc2a-4faf-89df-6f59755ed087)


完整如下
Active code page: 65001
venv dir exist

      Welcome to Streamlit!

      If you’d like to receive helpful onboarding emails, news, offers, promotions,
      and the occasional swag, please enter your email address below. Otherwise,
      leave this field blank.

      Email:  hotwater@gmail.com

  You can find our privacy policy at https://streamlit.io/privacy-policy

  Summary:
  - This open source library collects usage statistics.
  - We cannot see and do not store information contained inside Streamlit apps,
    such as text, charts, images, etc.
  - Telemetry data is stored in servers in the United States.
  - If you'd like to opt out, add the following to %userprofile%/.streamlit/config.toml,
    creating that file if necessary:

    [browser]
    gatherUsageStats = false


  You can now view your Streamlit app in your browser.

  URL: http://localhost:8501

load_config
Moonshot
Moonshot
Moonshot
Moonshot
Moonshot
Moonshot
C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\alinls\core.py:138: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
  if which is 'on_close':
Moonshot
Moonshot
Moonshot
Moonshot
Moonshot
Moonshot
Moonshot
main_try_test_audio begin
Speech synthesized to speaker for ssml
main_generate_ai_video begin:
main_generate_video_dubbing begin
use remote audio
C:\Users\admin\apps\MoneyPrinterPlus-4.2\work\1723184836393.wav
Speech synthesized for text [
        <speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
        <voice name="en-US-EmmaNeural">
            <prosody rate="0.00%">
                A glass of warm water awakens the body, hydrating the start of the day.
Just 10 minutes of simple exercise daily keeps you energized and strong.
A balanced breakfast fuels your body with essential nutrients for a productive day.
Maintain a positive mindset and smile at life each day.
A regular sleep schedule allows your body the time it needs to recover, ensuring quality rest.
A healthy life starts with every small detail. Let’s support each other in sharing a beautiful life.
Start your healthy lifestyle now!
            </prosody>
        </voice>
        </speak>
        ], and the audio was saved to [C:\Users\admin\apps\MoneyPrinterPlus-4.2\work\1723184836393.wav]
main_generate_video_dubbing end
main_generate_subtitle begin:
selected_audio_provider: Azure
Encountered error. Cancellation details: CancellationDetails(reason=CancellationReason.Error, error_details="Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://SERVICE_REGION.stt.speech.microsoft.com/speech/universal/v2
X-ConnectionId: 0e258339a26743188c1b7b2aca9f6338 SessionId: 0e258339a26743188c1b7b2aca9f6338")

Session stopped.
2024-08-09 00:27:16.590 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\pages\01_auto_video.py", line 66, in generate_video
    main_generate_ai_video(video_generator)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\main.py", line 268, in main_generate_ai_video
    main_generate_subtitle()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\main.py", line 257, in main_generate_subtitle
    generate_caption()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\captioning_service.py", line 75, in generate_caption
    captioning.finish()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\common_captioning_service.py", line 204, in finish
    for caption in self.captions_from_offline_results():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\common_captioning_service.py", line 187, in captions_from_offline_results
    last_caption = captions[-1]
                   ~~~~~~~~^^^^
IndexError: list index out of range
Moonshot
main_generate_video_content begin
llm_provider: Moonshot
keyword: health, morning routine, exercise, balanced breakfast, positive mindset
main_generate_video_content end
main_generate_ai_video begin:
main_generate_video_dubbing begin
use remote audio
C:\Users\admin\apps\MoneyPrinterPlus-4.2\work\1723185009273.wav
Speech synthesized for text [
        <speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
        <voice name="zh-CN-XiaoxiaoNeural">
            <prosody rate="0.00%">
                zh-CN:

新的一天，健康生活从清晨开始。当第一缕阳光透过窗帘，我们迎来了新的一天。这个时候，是开始健康生活的绝佳时机。首先，养成早起的习惯，让身体在清晨的空气中得到充分的休息和恢复。接着，进行适当的晨练，如散步、慢跑或瑜伽，以唤醒身体，增强体力。

此外，早餐也是健康生活的重要组成部分。选择营养均衡的早餐，如全麦面包、鸡蛋、牛奶和新鲜水果，为身体提供所需的能量和营养。同时，保持积极的心态，以乐观的心情迎接新的挑战。

最后，合理安排一天的工作和生活，避免过度劳累，保证充足的休息和睡眠。这样，我们就能以健康的身体和愉悦的心情，迎接每一个新的早晨，享受美好的生活。
            </prosody>
        </voice>
        </speak>
        ], and the audio was saved to [C:\Users\admin\apps\MoneyPrinterPlus-4.2\work\1723185009273.wav]
main_generate_video_dubbing end
main_generate_subtitle begin:
selected_audio_provider: Azure
Encountered error. Cancellation details: CancellationDetails(reason=CancellationReason.Error, error_details="Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://SERVICE_REGION.stt.speech.microsoft.com/speech/universal/v2
X-ConnectionId: d991d56f5c244b05b5d6a289beb34ddd SessionId: d991d56f5c244b05b5d6a289beb34ddd")

Session stopped.
2024-08-09 00:30:10.467 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\pages\01_auto_video.py", line 66, in generate_video
    main_generate_ai_video(video_generator)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\main.py", line 268, in main_generate_ai_video
    main_generate_subtitle()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\main.py", line 257, in main_generate_subtitle
    generate_caption()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\captioning_service.py", line 75, in generate_caption
    captioning.finish()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\common_captioning_service.py", line 204, in finish
    for caption in self.captions_from_offline_results():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\common_captioning_service.py", line 187, in captions_from_offline_results
    last_caption = captions[-1]
                   ~~~~~~~~^^^^
IndexError: list index out of range
main_generate_ai_video begin:
main_generate_video_dubbing begin
use remote audio
C:\Users\admin\apps\MoneyPrinterPlus-4.2\work\1723189076037.wav
Speech synthesized for text [
        <speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
        <voice name="zh-CN-XiaoxiaoNeural">
            <prosody rate="0.00%">
                zh-CN:

新的一天，健康生活从清晨开始。当第一缕阳光透过窗帘，我们迎来了新的一天。这个时候，是开始健康生活的绝佳时机。首先，养成早起的习惯，让身体在清晨的空气中得到充分的休息和恢复。接着，进行适当的晨练，如散步、慢跑或瑜伽，以唤醒身体，增强体力。

此外，早餐也是健康生活的重要组成部分。选择营养均衡的早餐，如全麦面包、鸡蛋、牛奶和新鲜水果，为身体提供所需的能量和营养。同时，保持积极的心态，以乐观的心情迎接新的挑战。

最后，合理安排一天的工作和生活，避免过度劳累，保证充足的休息和睡眠。这样，我们就能以健康的身体和愉悦的心情，迎接每一个新的早晨，享受美好的生活。
            </prosody>
        </voice>
        </speak>
        ], and the audio was saved to [C:\Users\admin\apps\MoneyPrinterPlus-4.2\work\1723189076037.wav]
main_generate_video_dubbing end
main_generate_subtitle begin:
selected_audio_provider: Azure
Encountered error. Cancellation details: CancellationDetails(reason=CancellationReason.Error, error_details="Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://SERVICE_REGION.stt.speech.microsoft.com/speech/universal/v2
X-ConnectionId: 4e48c21a3e81441fa6f345510dd47df0 SessionId: 4e48c21a3e81441fa6f345510dd47df0")

Session stopped.
2024-08-09 01:37:55.342 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\pages\01_auto_video.py", line 66, in generate_video
    main_generate_ai_video(video_generator)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\main.py", line 268, in main_generate_ai_video
    main_generate_subtitle()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\main.py", line 257, in main_generate_subtitle
    generate_caption()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\captioning_service.py", line 75, in generate_caption
    captioning.finish()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\common_captioning_service.py", line 204, in finish
    for caption in self.captions_from_offline_results():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\common_captioning_service.py", line 187, in captions_from_offline_results
    last_caption = captions[-1]
                   ~~~~~~~~^^^^
IndexError: list index out of range
main_generate_video_content begin
llm_provider: Moonshot
keyword: Healthy living, morning habits, exercise, nutrition, positive mindset, regular sleep
main_generate_video_content end
main_generate_ai_video begin:
main_generate_video_dubbing begin
use remote audio
C:\Users\admin\apps\MoneyPrinterPlus-4.2\work\1723189288996.wav
Speech synthesized for text [
        <speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
        <voice name="zh-CN-XiaoxiaoNeural">
            <prosody rate="0.00%">
                zh-CN: 健康生活始于晨间习惯。每天早晨，进行适量的运动，如散步或瑜伽，有助于唤醒身体，提高新陈代谢。同时 ，保持营养饮食，选择新鲜蔬果、全谷物和优质蛋白质，为身体提供必需的营养。此外，保持积极心态，面对挑战时保持乐观，有助于减轻压力，提高生活质量。最后，规律作息，确保每晚获得充足的睡眠，有助于身体恢复和精神焕发。通过这些简单的习惯，我们可以迈向更健康、更快乐的生活。
            </prosody>
        </voice>
        </speak>
        ], and the audio was saved to [C:\Users\admin\apps\MoneyPrinterPlus-4.2\work\1723189288996.wav]
main_generate_video_dubbing end
main_generate_subtitle begin:
selected_audio_provider: Azure
Encountered error. Cancellation details: CancellationDetails(reason=CancellationReason.Error, error_details="Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://SERVICE_REGION.stt.speech.microsoft.com/speech/universal/v2
X-ConnectionId: 93b74a1b551d499dace5c7b1177ea92b SessionId: 93b74a1b551d499dace5c7b1177ea92b")

Session stopped.
2024-08-09 01:41:31.071 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\pages\01_auto_video.py", line 66, in generate_video
    main_generate_ai_video(video_generator)
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\main.py", line 268, in main_generate_ai_video
    main_generate_subtitle()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\main.py", line 257, in main_generate_subtitle
    generate_caption()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\captioning_service.py", line 75, in generate_caption
    captioning.finish()
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\common_captioning_service.py", line 204, in finish
    for caption in self.captions_from_offline_results():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\apps\MoneyPrinterPlus-4.2\services\captioning\common_captioning_service.py", line 187, in captions_from_offline_results
    last_caption = captions[-1]
                   ~~~~~~~~^^^^
IndexError: list index out of range
Moonshot
Moonshot
Moonshot
Moonshot

**Comment by ddean2009** [comment]
SERVICE_REGION  ，微软的region没有填。

**Comment by city10666** [comment]
> region

region是啥？按照公众号那复制的，还是不行？难道公众号那框选的不对？
