### ISSUE TITLE
字幕生成报错

### ISSUE THREAD

**Issue by rm7rzedg** [ddean2009/MoneyPrinterPlus#31]
RT

```
Input #0, mp3, from 'G:\MoneyPrinterPlus\work\0.mp3':
  Metadata:
    encoder         : Lavf60.16.100
  Duration: 00:00:29.52, start: 0.023021, bitrate: 128 kb/s
  Stream #0:0: Audio: mp3 (mp3float), 48000 Hz, stereo, fltp, 128 kb/s
      Metadata:
        encoder         : Lavf
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'G:\MoneyPrinterPlus\work\1725429008785.wav':
  Metadata:
    ISFT            : Lavf61.5.101
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, stereo, s16, 1536 kb/s
      Metadata:
        encoder         : Lavc61.11.100 pcm_s16le
[out#0/wav @ 0000011bf7194e80] video:0KiB audio:5530KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.001377%
size=    5530KiB time=00:00:29.49 bitrate=1536.0kbits/s speed= 906x
Extracted files into G:\MoneyPrinterPlus\work\1725429008785.wav
main_generate_video_dubbing end
main_generate_subtitle begin:
selected_audio_provider: fasterwhisper
G:\MoneyPrinterPlus\fasterwhisper\tiny False
2024-09-04 13:50:49.301 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\shira\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
  File "C:\Users\shira\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "C:\Users\shira\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\state\session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
  File "C:\Users\shira\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\state\session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "C:\Users\shira\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\state\session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
  File "G:\MoneyPrinterPlus\pages\01_auto_video.py", line 75, in generate_video
    main_generate_ai_video(video_generator)
  File "G:\MoneyPrinterPlus\main.py", line 287, in main_generate_ai_video
    main_generate_subtitle()
  File "G:\MoneyPrinterPlus\main.py", line 276, in main_generate_subtitle
    generate_caption()
  File "G:\MoneyPrinterPlus\services\captioning\captioning_service.py", line 68, in generate_caption
    result_list = fasterwhisper_service.process(get_session_option("audio_output_file"),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\MoneyPrinterPlus\services\audio\faster_whisper_recognition_service.py", line 51, in process
    model = WhisperModel(convert_module_to_path(self.model_name), device=self.device_type, compute_type=self.compute_type,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shira\AppData\Local\Programs\Python\Python312\Lib\site-packages\faster_whisper\transcribe.py", line 139, in __init__
    model_path = download_model(
                 ^^^^^^^^^^^^^^^
  File "C:\Users\shira\AppData\Local\Programs\Python\Python312\Lib\site-packages\faster_whisper\utils.py", line 78, in download_model
    raise ValueError(
ValueError: Invalid model size 'G:\MoneyPrinterPlus\fasterwhisper\tiny', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large-v3, large, distil-large-v2, distil-medium.en, distil-small.en, distil-large-v3
```

**Comment by ddean2009** [comment]
fasterwhisper 的模型没有下载好， 看我我的教程：  [fasterWhisper和MoneyPrinterPlus无缝集成](https://mp.weixin.qq.com/s/dSZjpfqUKBz3PyAOYvJKGw)
