### ISSUE TITLE
No module named 'langchain_community.llms.moonshot'

### ISSUE THREAD

**Issue by jeffreyrobeson** [ddean2009/MoneyPrinterPlus#5]
Traceback (most recent call last):
  File "F:\pinokio\bin\miniconda\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "F:\aigc\MoneyPrinterPlus\pages\01_auto_video.py", line 5, in <module>
    from main import main_generate_video_content, main_generate_ai_video, main_generate_video_dubbing, \
  File "F:\aigc\MoneyPrinterPlus\main.py", line 11, in <module>
    from services.llm.baichuan_service import MyBaichuanService
  File "F:\aigc\MoneyPrinterPlus\services\llm\baichuan_service.py", line 8, in <module>
    from langchain_community.llms.moonshot import Moonshot
ModuleNotFoundError: No module named 'langchain_community.llms.moonshot'

**Comment by ddean2009** [comment]
pip install -r requirement.txt  执行了吗？
