### ISSUE TITLE
报缺失missing 2 required positional arguments: 'application' and 'request'

### ISSUE THREAD

**Issue by luyoujie1989** [ddean2009/MoneyPrinterPlus#57]
2024-09-24 17:52:53.622 Uncaught exception
Traceback (most recent call last):
  File "D:\py\MoneyPrinterPlus-main\venv\lib\site-packages\tornado\http1connection.py", line 278, in _read_message
    delegate.finish()
  File "D:\py\MoneyPrinterPlus-main\venv\lib\site-packages\tornado\routing.py", line 268, in finish
    self.delegate.finish()
  File "D:\py\MoneyPrinterPlus-main\venv\lib\site-packages\tornado\web.py", line 2399, in finish
    self.execute()
  File "D:\py\MoneyPrinterPlus-main\venv\lib\site-packages\tornado\web.py", line 2421, in execute
    self.handler = self.handler_class(
  File "D:\py\MoneyPrinterPlus-main\venv\lib\site-packages\tornado\websocket.py", line 220, in __init__
    super().__init__(application, request, **kwargs)
  File "D:\py\MoneyPrinterPlus-main\venv\lib\site-packages\tornado\web.py", line 214, in __init__
    super().__init__()
  File "D:\syssoft\py\lib\typing.py", line 1422, in _no_init_or_replace_init
    cls.__init__(self, *args, **kwargs)
TypeError: WebSocketHandler.__init__() missing 2 required positional arguments: 'application' and 'request'

**Comment by ddean2009** [comment]
依赖没装好？
