### ISSUE TITLE
添加字幕过程中报错

### ISSUE THREAD

**Issue by KFK121** [ddean2009/MoneyPrinterPlus#64]
## 浏览器页面

CalledProcessError: Command '['ffmpeg', '-i', '/home/MoneyPrinter/MoneyPrinterPlus/final/final-1728287634716.mp4', '-vf', "subtitles=/home/MoneyPrinter/MoneyPrinterPlus/work/1728287586947.srt:fontsdir=/home/MoneyPrinter/MoneyPrinterPlus/fonts:force_style='Fontname=Songti SC Light,Fontsize=6,Alignment=2,MarginV=16,MarginL=4,MarginR=4,BorderStyle=1,Outline=0,Shadow=0,PrimaryColour=&HFFFFFF&,OutlineColour=&H000000&,Spacing=2'", '-y', '/home/MoneyPrinter/MoneyPrinterPlus/final/final-1728287634716.temp.mp4']' returned non-zero exit status 234.
Traceback:
File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
File "/home/MoneyPrinter/MoneyPrinterPlus/pages/01_auto_video.py", line 98, in generate_video
    main_generate_ai_video(video_generator)
File "/home/MoneyPrinter/MoneyPrinterPlus/main.py", line 324, in main_generate_ai_video
    add_subtitles(video_file, subtitle_file,
File "/home/MoneyPrinter/MoneyPrinterPlus/services/captioning/captioning_service.py", line 123, in add_subtitles
    subprocess.run(ffmpeg_cmd, check=True)
File "/home/anaconda3/envs/mp/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,

## 命令行界面：
['ffmpeg', '-i', '/home/MoneyPrinter/MoneyPrinterPlus/final/final-1728287634716.mp4', '-i', '/home/MoneyPrinter/MoneyPrinterPlus/bgmusic/1.mp3', '-filter_complex', '[1:a]aloop=loop=0:size=100M[bgm];[bgm]volume=0.3[bgm_vol];[0:a][bgm_vol]amix=duration=first:dropout_transition=3:inputs=2[a]', '-map', '0:v', '-map', '[a]', '-c:v', 'copy', '-shortest', '/home/MoneyPrinter/MoneyPrinterPlus/final/final-1728287634716.temp.mp4']
final file without subtitle: /home/MoneyPrinter/MoneyPrinterPlus/final/final-1728287634716.mp4
ffmpeg -i /home/MoneyPrinter/MoneyPrinterPlus/final/final-1728287634716.mp4 -vf subtitles=/home/MoneyPrinter/MoneyPrinterPlus/work/1728287586947.srt:fontsdir=/home/MoneyPrinter/MoneyPrinterPlus/fonts:force_style='Fontname=Songti SC Light,Fontsize=6,Alignment=2,MarginV=16,MarginL=4,MarginR=4,BorderStyle=1,Outline=0,Shadow=0,PrimaryColour=&HFFFFFF&,OutlineColour=&H000000&,Spacing=2' -y /home/MoneyPrinter/MoneyPrinterPlus/final/final-1728287634716.temp.mp4
ffmpeg version 6.1.2 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-44)
  configuration: --enable-ffplay
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/MoneyPrinter/MoneyPrinterPlus/final/final-1728287634716.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf60.16.100
  Duration: 00:00:15.65, start: 0.000000, bitrate: 1856 kb/s
  Stream #0:0[0x1](und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p(tv, bt709), 1080x1920 [SAR 1:1 DAR 9:16], 1786 kb/s, 20 fps, 20 tbr, 10240 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.31.102 mpeg4
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 65 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[AVFilterGraph @ 0x4451940] No option name near '/home/MoneyPrinter/MoneyPrinterPlus/work/1728287586947.srt:fontsdir=/home/MoneyPrinter/MoneyPrinterPlus/fonts:force_style=Fontname=Songti SC Light,Fontsize=6,Alignment=2,MarginV=16,MarginL=4,MarginR=4,BorderStyle=1,Outline=0,Shadow=0,PrimaryColour=&HFFFFFF&,OutlineColour=&H000000&,Spacing=2'
[AVFilterGraph @ 0x4451940] Error parsing a filter description around: 
[AVFilterGraph @ 0x4451940] Error parsing filterchain 'subtitles=/home/MoneyPrinter/MoneyPrinterPlus/work/1728287586947.srt:fontsdir=/home/MoneyPrinter/MoneyPrinterPlus/fonts:force_style='Fontname=Songti SC Light,Fontsize=6,Alignment=2,MarginV=16,MarginL=4,MarginR=4,BorderStyle=1,Outline=0,Shadow=0,PrimaryColour=&HFFFFFF&,OutlineColour=&H000000&,Spacing=2'' around: 
[vost#0:0/mpeg4 @ 0x4450b40] Error initializing a simple filtergraph
Error opening output file /home/MoneyPrinter/MoneyPrinterPlus/final/final-1728287634716.temp.mp4.
Error opening output files: Invalid argument
2024-10-07 15:53:48.963 Uncaught app exception
Traceback (most recent call last):
  File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
  File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
  File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "/home/anaconda3/envs/mp/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
  File "/home/MoneyPrinter/MoneyPrinterPlus/pages/01_auto_video.py", line 98, in generate_video
    main_generate_ai_video(video_generator)
  File "/home/MoneyPrinter/MoneyPrinterPlus/main.py", line 324, in main_generate_ai_video
    add_subtitles(video_file, subtitle_file,
  File "/home/MoneyPrinter/MoneyPrinterPlus/services/captioning/captioning_service.py", line 123, in add_subtitles
    subprocess.run(ffmpeg_cmd, check=True)
  File "/home/anaconda3/envs/mp/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-i', '/home/MoneyPrinter/MoneyPrinterPlus/final/final-1728287634716.mp4', '-vf', "subtitles=/home/MoneyPrinter/MoneyPrinterPlus/work/1728287586947.srt:fontsdir=/home/MoneyPrinter/MoneyPrinterPlus/fonts:force_style='Fontname=Songti SC Light,Fontsize=6,Alignment=2,MarginV=16,MarginL=4,MarginR=4,BorderStyle=1,Outline=0,Shadow=0,PrimaryColour=&HFFFFFF&,OutlineColour=&H000000&,Spacing=2'", '-y', '/home/MoneyPrinter/MoneyPrinterPlus/final/final-1728287634716.temp.mp4']' returned non-zero exit status 234.

**Comment by ddean2009** [comment]
ffmpeg 版本不对：  AVFilterGraph @ 0x4451940] No option name near  

ffmpeg 6.1.1 安装包：https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-6.1.1-essentials_build.zip
