### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 34: invalid start byte

### ISSUE THREAD

**Issue by fadeway32** [ddean2009/MoneyPrinterPlus#79]
Traceback (most recent call last):
  File "D:\Program Files\python\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
  File "D:\Program Files\python\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
  File "D:\Program Files\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
  File "D:\Program Files\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
  File "D:\Program Files\python\Lib\site-packages\streamlit\runtime\state\session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
  File "E:\program\code1\MoneyPrinterPlus\pages\02_mix_video.py", line 95, in generate_video_for_mix
    main_generate_ai_video_for_mix(video_generator)
  File "E:\program\code1\MoneyPrinterPlus\main.py", line 342, in main_generate_ai_video_for_mix
    main_generate_video_dubbing_for_mix()
  File "E:\program\code1\MoneyPrinterPlus\main.py", line 187, in main_generate_video_dubbing_for_mix
    audio_output_file_list, video_dir_list = get_audio_and_video_list(audio_service, audio_rate)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\program\code1\MoneyPrinterPlus\services\hunjian\hunjian_service.py", line 75, in get_audio_and_video_list
    video_scene_text_list = get_video_scene_text_list(video_text_list)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\program\code1\MoneyPrinterPlus\services\hunjian\hunjian_service.py", line 61, in get_video_scene_text_list
    video_line = random_line_from_text_file(video_text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\program\code1\MoneyPrinterPlus\tools\file_utils.py", line 145, in random_line_from_text_file
    line = random_line(file)
           ^^^^^^^^^^^^^^^^^
  File "E:\program\code1\MoneyPrinterPlus\tools\file_utils.py", line 35, in random_line
    lines = afile.readlines()
            ^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 34: invalid start byte

**Comment by zhengb0** [comment]
请问解决了吗？
