### ISSUE TITLE
混剪提示：目录无权限

### ISSUE THREAD

**Issue by zyhxq** [ddean2009/MoneyPrinterPlus#90]
混剪提示：目录无权限，这个目录必须要是项目目录吗
`ermissionError: [Errno 13] Permission denied: 'F:\\自媒体\\小说推文\\TK\\素材\\炼丹炉\\test1'
Traceback:
File "D:\Program Files\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 575, in _run_script
    self._session_state.on_script_will_rerun(
File "D:\Program Files\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 65, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
File "D:\Program Files\Lib\site-packages\streamlit\runtime\state\session_state.py", line 517, in on_script_will_rerun
    self._call_callbacks()
File "D:\Program Files\Lib\site-packages\streamlit\runtime\state\session_state.py", line 530, in _call_callbacks
    self._new_widget_state.call_callback(wid)
File "D:\Program Files\Lib\site-packages\streamlit\runtime\state\session_state.py", line 274, in call_callback
    callback(*args, **kwargs)
File "E:\opensource\MoneyPrinterPlus\pages\02_mix_video.py", line 95, in generate_video_for_mix
    main_generate_ai_video_for_mix(video_generator)
File "E:\opensource\MoneyPrinterPlus\main.py", line 342, in main_generate_ai_video_for_mix
    main_generate_video_dubbing_for_mix()
File "E:\opensource\MoneyPrinterPlus\main.py", line 196, in main_generate_video_dubbing_for_mix
    audio_output_file_list, video_dir_list = get_audio_and_video_list_local(audio_service)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\opensource\MoneyPrinterPlus\services\hunjian\hunjian_service.py", line 99, in get_audio_and_video_list_local
    video_scene_text_list = get_video_scene_text_list(video_text_list)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\opensource\MoneyPrinterPlus\services\hunjian\hunjian_service.py", line 61, in get_video_scene_text_list
    video_line = random_line_from_text_file(video_text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\opensource\MoneyPrinterPlus\tools\file_utils.py", line 144, in random_line_from_text_file
    with open(text_file, 'r', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
![image](https://github.com/user-attachments/assets/2ec02d79-e098-4413-9ee1-cb94fb3fa556)

**Comment by zyhxq** [comment]
`The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "E:\opensource\MoneyPrinterPlus\pages\02_merge_video.py", line 245, in <module>
    st.video(result_video_file)
  File "D:\Program Files\Lib\site-packages\streamlit\runtime\metrics_util.py", line 397, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Lib\site-packages\streamlit\elements\media.py", line 341, in video
    marshall_video(
  File "D:\Program Files\Lib\site-packages\streamlit\elements\media.py", line 531, in marshall_video
    _marshall_av_media(coordinates, proto, data, mimetype)
  File "D:\Program Files\Lib\site-packages\streamlit\elements\media.py", line 438, in _marshall_av_media
    file_url = runtime.get_instance().media_file_mgr.add(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 224, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'E:\opensource\MoneyPrinterPlus\final\final-1733149521674.mp4'`

![image](https://github.com/user-attachments/assets/2807d383-9a87-4e6b-9b99-dcc4e6daa0c9)
